[package]
name = "characterize"
version = "0.1.0"
edition = "2021"

[dependencies]
ab_glyph = "0.2.29"
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
image = "0.25.5"
imageproc = "0.25.0"
rand = "0.8.5"
